### ISSUE TITLE
Feat: TODO 11/07

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [TEAM-LINRING/LINRING-FRONT-FLUTTER#69]
**✍ Description**
 NOTION 페이지 참고

**📋 To do**
- [ ]  태그추가 disable( 한줄소개도 필수로해)
- [ ]  채팅 목록 프로필, 채팅방 디자인 변경 적용
- [ ]  설정에 데이터 및 페이지 연결 (프로필 이미지도)
- [ ]  fcm 설정
- [ ]  시스템 메시지 (재영) 제작 이후 연결
- [ ]  로딩 페이지로 연결

**➕ Etc.**
기능 요청에 대한 부가 설명이 필요한 경우에 작성해주세요.
